### PR TITLE
Remove blackfire.io support because of segfault caused by pthreads

### PR DESCRIPTION
**Pull request by wagnert**

### CODE REVIEW

**Comment by smolinari** [comment]
That's a bummer....

Scott

**Comment by wagnert** [comment]
I had a long discussion with them, finally they said it would be too much effort to make it work with pthreads. So actually XDebug is the only solution someone can use for profiling.

**Comment by smolinari** [comment]
I thought xdebug was also not working with appserver for any kind of debugging purposes. 

Scott

**Comment by wagnert** [comment]
XDebug works for profiling, not for debugging, that's correct :( But blackfire also provides profiling functionality only, so XDebug can be a replacement for blackfire, although blackfire is much more comfortable to use.

**Comment by smolinari** [comment]
Ok. Understand now. 

Will the same issues with xdebug be a problem with the move to pthreads 3.0 and PHP7? 

It is a shame xdebug doesn't work. 

Scott

**Comment by wagnert** [comment]
There is a issue where a someone mentioned to work with [pthreads 3, PHP7 and XDebug](https://github.com/krakjoe/pthreads/issues/467), so hopefully the problems can be solved then :)

**Comment by smolinari** [comment]
Check out the last reply from RyanNerd in that thread. Looks like getting appserver onto V3 of pthreads and PHP7 means also getting xdebug support. :smile: 

Scott

**Pull request merged**
