### PR TITLE
travis: PHP 5.6 and 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**
See http://docs.travis-ci.com/user/languages/php/#PHP-7

Composer allows them both (with PHP >= 5.4), so they should be tested as well.

### CODE REVIEW

**Comment by wick-ed** [comment]
Hi @TomasVotruba ,

nice idea but we do rely heavily on the pthreads extension which does not have support for PHP7 by now.
Could you make the 1.0 build optional/able to fail without a general build fail?

**Comment by TomasVotruba** [comment]
@wick-ed I see. Sure I can add it to allowed failures.

Looks like now it fails with Code sniffer: https://travis-ci.org/appserver-io/appserver/jobs/52401209

Why not prefer more modern PHAR or composer? [PEAR is slowly deprecating](https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method).

Also where is Code sniffer used? I could not find it in `.travis.yml`.

**Comment by wick-ed** [comment]
@TomasVotruba ,

you are right. The pyrus installation is indeed something out of old times. 
I will remove it as we already require it for our [build package](https://github.com/appserver-io/build)
That's where the codesniffer gets called ultimately.
The `composer-init` target loads the dependencies and therefor provides the `build` target which includes phpcs.

**Comment by TomasVotruba** [comment]
@wick-ed I see. Great idea with standalone build repo. I was looking for something like that to include to my OS projects.

> I will remove it as we already require it for our build package

So I can remove it in this PR?

**Comment by TomasVotruba** [comment]
I see you're doing it already in another PR.

This PR is ready then.

**Comment by wick-ed** [comment]
Thanks. :)
Feel free to use it.

You can, or merge upstream master as soon as my pull request gets merged.

**Comment by wick-ed** [comment]
> This PR is ready then.

Great! Will merge it as soon as travis is ready.
Thanks for contributing. :)

**Comment by TomasVotruba** [comment]
Thanks!

**Pull request merged**
