### PR TITLE
[TASK] database provisioning should be possible with MySQL PDO

### PR DESCRIPTION
**Pull request by hhoechtl**
Addresses #770

### CODE REVIEW

**Comment by wick-ed** [comment]
test this please

**Comment by hhoechtl** [comment]
Who do you mean? I have tested it locally before pushing it

**Comment by wick-ed** [comment]
Hi @hhoechtl , no offense meant!
This is the trigger phrase for our Jenkins tests. We might rephrase that to avoid confusion. :)

But could you fix the coding style? It contains tabs instead of spaces.
Thanks :)

**Comment by hhoechtl** [comment]
Ah, your jenkins trigger sounds like a "call to action" for the pull request author ^^

CGL done

**Comment by wick-ed** [comment]
Does Jenkins approve?

**Comment by wick-ed** [comment]
ci.start

**Comment by wick-ed** [comment]
test this please

**Comment by hhoechtl** [comment]
Oh, your Jenkins seems not very communicative

**Comment by wick-ed** [comment]
Hmmm, it seems Jenkins even caches the trigger phrases. Will restart it later.
After that every miss-communication should be gone. :)

**Pull request merged**
