### PR TITLE
Final update 

### PR DESCRIPTION
**Pull request by smolinari**
A lot of corrections. :smile: 

Please make sure lines 1058-1059 are technically and factually correct.

I hope the rest is to your satisfaction too!

Scott

### CODE REVIEW

**Comment by wick-ed** [comment]
Merged it, thanks a lot :)

**Comment by smolinari** [comment]
No problem. I'll be moving on to the docs pages next. 

Scott

**Comment by smolinari** [comment]
Ah, and If you want, you might change the title to "Final update to the readme.md file". It looks better, should someone be looking at changes. I didn't consider how it might catch attention unnecessarily, with the title to general like that. I'll make sure to do better next PR.

Scott

**Comment by wick-ed** [comment]
Made the change, thanks. :+1:

**Pull request merged**
