### PR TITLE
[FIX] initialize configurationService before it is used

### LINKED ISSUE #769: [appserver-io/appserver] undeclared configuration service variable
@see https://github.com/appserver-io/appserver/blob/master/src/AppserverIo/Appserver/Core/GenericDeployment.php#L63

### PR DESCRIPTION
**Pull request by hhoechtl**
Resolves #769

### CODE REVIEW

**Comment by wick-ed** [comment]
Hi @hhoechtl , thanks for the fix.
Could you make the assignment above the `foreach` statement so it will not be re-done on every iteration?

**Comment by hhoechtl** [comment]
Jenkins?

**Comment by wick-ed** [comment]
test this please

**Comment by zelgerj** [comment]
@appserver-ci test this please

**Comment by wick-ed** [comment]
Does sound better @hhoechtl ? ;)

**Comment by hhoechtl** [comment]
@wick-ed Yes it does. Reduces confusion (y)

**Pull request merged**
