### PR TITLE
Changed introduction text (suggestion).

### PR DESCRIPTION
**Pull request by smolinari**

### CODE REVIEW

**Comment by wick-ed** [comment]
Hi @smolinari , thanks for the contribution! :)

Even though it is very well written it does seem a bit lengthy and one sided (just focuses on the webserver part) for a general introduction.

Could you also make it `appserver.io` (all lowercase)?

Thanks. :+1:

**Comment by smolinari** [comment]
No problem.

Scott

**Comment by wick-ed** [comment]
Hi @smolinari ,

I meant not to abandon the PR completely, just shrink the article in size. :)

Regards, Bernhard

**Comment by smolinari** [comment]
Ok. Another try. I actually like it better this time. I've also started to correct the rest of the file too.

Scott

**Comment by wick-ed** [comment]
Great work! Thanks :D

**Pull request merged**
