### PR TITLE
[FIX] mandatory parameter path is only necessary for sqlite

### PR DESCRIPTION
**Pull request by hhoechtl**

### CODE REVIEW

**Comment by zelgerj** [comment]
restest this please

**Comment by zelgerj** [comment]
Hi Hans,

thanks for that. Just a little thing... would it be possible to refactor it like this...
```php
if ($databaseNode->getPath()) { …
```
instead of using that `instanceof` thing? Could you test that?
We think its better to not make the implemented code depending to classnames that could be changed or deleted in the future.

Thanks for your time!

**Comment by hhoechtl** [comment]
Changed it and it works. No classname dependency anymore

**Comment by zelgerj** [comment]
retest it please

**Comment by zelgerj** [comment]
restest this please

**Comment by zelgerj** [comment]
Looks good, Thanks for that! :+1:

**Pull request merged**
