### PR TITLE
Add Rout.Lt package to appserver.io distribution

### PR DESCRIPTION
**Pull request by wagnert**

### CODE REVIEW

**Comment by smolinari** [comment]
Nice! :+1: 

What would be the steps necessary to use routlt in an app, now that it is part of the core? I would guess, the same configuration is needed in the app, but now the routlt package doesn't need to be installed within the app, correct? 

Would that also mean the routlt-project needs to be changed too? 

Scott

**Comment by wagnert** [comment]
Actually there is nothing we've to change, because the configuration is the same. Only the autoloader will find the `appserver-io/routlt` files in the core vendor directory instead of the application's vendor directory.  The `appserver-io/routlt` package doesn't need to be installed with the application any longer :)

In the `routlt-project` i would actually prefer to install the specified Rout.Lt version with the application, till `appserver-cli` will replace it, what do you think?

**Comment by smolinari** [comment]
Ach ja! Ok. I forgot about the versioning issue. So, I am happy.then. :+1: 

It is going to be interesting to see, if I can get the routlt base project going with the CLI correctly. Ant does do quite a bit of work. :smile: 

Scott

**Comment by wagnert** [comment]
Indeed, ANT does do a whole lot of stuff, but i think it should be possible :)

Tim

**Pull request merged**
