### PR TITLE
Add blog post for version 1.1.0

### PR DESCRIPTION
**Pull request by wagnert**

### CODE REVIEW

**Comment by smolinari** [comment]
Once this PR is merged, I can go through and proof read the post for you and do some correcting, if you'd like.

Or will the post automatically be published on the site live, once it is merged? If so, I'll fork your fork. LOL! That sound funny.

Scott

**Comment by wagnert** [comment]
@smolinari This would be really nice, Scott. I think we'll merge the post during the next 1 - 2 hours, so a PR would be very welcome ;)

**Comment by smolinari** [comment]
I'd definitely like to help on this. However, I can only do the proof read, when I am at home. Approximately 7 p.m. 

Scott

**Comment by wagnert** [comment]
@smolinari That's totally o. k., thanks Scott :)

**Comment by smolinari** [comment]
Just to be sure. You'll be merging this PR in a couple of hours?

Scott

**Comment by wagnert** [comment]
I can do this, if you think it's better ;) Optional i can merge it the next 30 minutes and you make a PR at around 7 pm?

**Comment by smolinari** [comment]
I need this PR to be merged into the repo, so I can pull the new blog post into my fork to do the proofread and make any changes. If that isn't possicle, I'd need to access to your fork and update the post directly: Or, I can fork your fork and do a PR to your fork. 

My PR will come a bit later. Probably around 9 p.m. or so. 

Scott

**Comment by smolinari** [comment]
Will you also be available on Gitter, in case I have some questions to meanings?

Scott

**Comment by wagnert** [comment]
Ok, so i'll merge it the next 30 minutes and you can send your PM at round about 9:00 pm :) ... i've a date with my fitness studio tonight, but i'll try my best to be online, optional you can ask Hans or Berni :)

**Comment by smolinari** [comment]
Ok. Have fun in the fitness Studio!

Scott

**Comment by wagnert** [comment]
Thanks, i will for sure :)

**Pull request merged**
